// Code generated by protoc-gen-psrpc v0.6.0, DO NOT EDIT.
// source: rpc/ddt.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)
import livekit1 "github.com/livekit/protocol/livekit"
import livekit6 "github.com/livekit/protocol/livekit"

var _ = version.PsrpcVersion_0_6

// ===========================
// DdtManager Client Interface
// ===========================

type DdtManagerClient[NodeIdTopicType ~string] interface {
	Callout(ctx context.Context, nodeId NodeIdTopicType, req *livekit6.CreateRoomRequest, opts ...psrpc.RequestOption) (*livekit1.Room, error)

	Huangup(ctx context.Context, nodeId NodeIdTopicType, req *livekit6.CreateRoomRequest, opts ...psrpc.RequestOption) (*livekit1.Room, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ===============================
// DdtManager ServerImpl Interface
// ===============================

type DdtManagerServerImpl interface {
	Callout(context.Context, *livekit6.CreateRoomRequest) (*livekit1.Room, error)

	Huangup(context.Context, *livekit6.CreateRoomRequest) (*livekit1.Room, error)
}

// ===========================
// DdtManager Server Interface
// ===========================

type DdtManagerServer[NodeIdTopicType ~string] interface {
	RegisterCalloutTopic(nodeId NodeIdTopicType) error
	DeregisterCalloutTopic(nodeId NodeIdTopicType)
	RegisterHuangupTopic(nodeId NodeIdTopicType) error
	DeregisterHuangupTopic(nodeId NodeIdTopicType)
	RegisterAllNodeTopics(nodeId NodeIdTopicType) error
	DeregisterAllNodeTopics(nodeId NodeIdTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =================
// DdtManager Client
// =================

type ddtManagerClient[NodeIdTopicType ~string] struct {
	client *client.RPCClient
}

// NewDdtManagerClient creates a psrpc client that implements the DdtManagerClient interface.
func NewDdtManagerClient[NodeIdTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (DdtManagerClient[NodeIdTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "DdtManager",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("Callout", false, false, true, true)
	sd.RegisterMethod("Huangup", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &ddtManagerClient[NodeIdTopicType]{
		client: rpcClient,
	}, nil
}

func (c *ddtManagerClient[NodeIdTopicType]) Callout(ctx context.Context, nodeId NodeIdTopicType, req *livekit6.CreateRoomRequest, opts ...psrpc.RequestOption) (*livekit1.Room, error) {
	return client.RequestSingle[*livekit1.Room](ctx, c.client, "Callout", []string{string(nodeId)}, req, opts...)
}

func (c *ddtManagerClient[NodeIdTopicType]) Huangup(ctx context.Context, nodeId NodeIdTopicType, req *livekit6.CreateRoomRequest, opts ...psrpc.RequestOption) (*livekit1.Room, error) {
	return client.RequestSingle[*livekit1.Room](ctx, c.client, "Huangup", []string{string(nodeId)}, req, opts...)
}

func (s *ddtManagerClient[NodeIdTopicType]) Close() {
	s.client.Close()
}

// =================
// DdtManager Server
// =================

type ddtManagerServer[NodeIdTopicType ~string] struct {
	svc DdtManagerServerImpl
	rpc *server.RPCServer
}

// NewDdtManagerServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewDdtManagerServer[NodeIdTopicType ~string](svc DdtManagerServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (DdtManagerServer[NodeIdTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "DdtManager",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("Callout", false, false, true, true)
	sd.RegisterMethod("Huangup", false, false, true, true)
	return &ddtManagerServer[NodeIdTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *ddtManagerServer[NodeIdTopicType]) RegisterCalloutTopic(nodeId NodeIdTopicType) error {
	return server.RegisterHandler(s.rpc, "Callout", []string{string(nodeId)}, s.svc.Callout, nil)
}

func (s *ddtManagerServer[NodeIdTopicType]) DeregisterCalloutTopic(nodeId NodeIdTopicType) {
	s.rpc.DeregisterHandler("Callout", []string{string(nodeId)})
}

func (s *ddtManagerServer[NodeIdTopicType]) RegisterHuangupTopic(nodeId NodeIdTopicType) error {
	return server.RegisterHandler(s.rpc, "Huangup", []string{string(nodeId)}, s.svc.Huangup, nil)
}

func (s *ddtManagerServer[NodeIdTopicType]) DeregisterHuangupTopic(nodeId NodeIdTopicType) {
	s.rpc.DeregisterHandler("Huangup", []string{string(nodeId)})
}

func (s *ddtManagerServer[NodeIdTopicType]) allNodeTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterCalloutTopic, s.DeregisterCalloutTopic),
		server.NewRegisterer(s.RegisterHuangupTopic, s.DeregisterHuangupTopic),
	}
}

func (s *ddtManagerServer[NodeIdTopicType]) RegisterAllNodeTopics(nodeId NodeIdTopicType) error {
	return s.allNodeTopicRegisterers().Register(nodeId)
}

func (s *ddtManagerServer[NodeIdTopicType]) DeregisterAllNodeTopics(nodeId NodeIdTopicType) {
	s.allNodeTopicRegisterers().Deregister(nodeId)
}

func (s *ddtManagerServer[NodeIdTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *ddtManagerServer[NodeIdTopicType]) Kill() {
	s.rpc.Close(true)
}

var psrpcFileDescriptor11 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xcf, 0x4d, 0x4a, 0x06, 0x31,
	0x0c, 0x06, 0x60, 0x8a, 0xe2, 0x07, 0x85, 0x01, 0x2d, 0x0a, 0xda, 0x8d, 0xe8, 0x01, 0x5a, 0xd0,
	0x1b, 0x38, 0x2e, 0xdc, 0x88, 0x30, 0x4b, 0x37, 0x43, 0xa7, 0x0d, 0x63, 0xb1, 0x6d, 0x6a, 0x27,
	0xf5, 0x0e, 0x5e, 0xc6, 0x85, 0x27, 0x94, 0xf9, 0xf3, 0x04, 0x6e, 0x02, 0x79, 0x92, 0xbc, 0x10,
	0xde, 0x94, 0x6c, 0xb5, 0x73, 0xa4, 0x72, 0x41, 0x42, 0x71, 0x54, 0xb2, 0x95, 0x0d, 0x66, 0xf2,
	0x98, 0xa6, 0xd5, 0xe4, 0x79, 0xf0, 0x9f, 0xf0, 0xee, 0xa9, 0x8f, 0xe8, 0x20, 0xec, 0x2a, 0x76,
	0x2d, 0x88, 0x71, 0xb5, 0xbb, 0x6f, 0xc6, 0xf9, 0xa3, 0xa3, 0x67, 0x93, 0xcc, 0x08, 0x45, 0xbc,
	0xf0, 0x43, 0x6b, 0x42, 0xc0, 0x4a, 0x42, 0xaa, 0x6d, 0x5d, 0xb5, 0x05, 0x0c, 0x41, 0x87, 0x18,
	0x3b, 0xf8, 0xa8, 0x30, 0x91, 0x6c, 0xfe, 0x66, 0xb3, 0xde, 0x5e, 0xfd, 0x7c, 0xb1, 0x8b, 0x53,
	0x26, 0xcf, 0xf8, 0x71, 0x42, 0x07, 0xe2, 0x30, 0xd7, 0xde, 0xbb, 0x4b, 0x36, 0x07, 0x3e, 0x55,
	0x93, 0xc6, 0x9a, 0xff, 0x27, 0xf0, 0xe1, 0xe6, 0xf5, 0x7a, 0xf4, 0xf4, 0x56, 0x07, 0x65, 0x31,
	0xea, 0xed, 0x4a, 0x2f, 0xcf, 0x58, 0x0c, 0xba, 0x64, 0x3b, 0x9c, 0x2c, 0xdd, 0xfd, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x37, 0x5d, 0x54, 0x71, 0x29, 0x01, 0x00, 0x00,
}
